defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:10.15.3-browsers

version: 2
jobs:
  build:
    <<: *defaults
    working_directory: ~/app
    steps:
      - run:
          name: Generate Build version
          command: |
            echo "export BUILD_VERSION=$(date +%Y%m%d%H%M)-$CIRCLE_BUILD_NUM" >> $BASH_ENV
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: yarn test
      - setup_remote_docker
      - deploy:
          name: Push to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build . \
                --tag "mojdigitalstudio/health-kick:$BUILD_VERSION" \
                --label "maintainer=noms-studio-webops@digital.justice.gov.uk" \
                --label "build.number=$CIRCLE_BUILD_NUM" \
                --label "build.url=$CIRCLE_BUILD_URL" \
                --label "build.gitref=$CIRCLE_SHA1"
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
              docker push mojdigitalstudio/health-kick:$BUILD_VERSION
            fi
      - deploy:
          name: Install elastic beanstalk CLI
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              sudo apt-get update
              sudo apt-get --assume-yes install python3-pip python-dev
              pip3 install --user 'six>-1.9.0' awsebcli --ignore-installed
            fi
      - deploy:
          name: Deploy to Elastic Beanstalk Staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              yarn run plant-beanstalk $BUILD_VERSION
              ~/.local/bin/eb deploy --process --verbose
            fi

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/